const NB_GENERAL_SERIES = 3;
const NB_MEMORIES_PER_SERIES = 16;
const NB_INST_IOSERIES = 64;
const NB_INST_PER_MEM = 4;
const NB_INST_PER_SERIES = NB_INST_PER_MEM * NB_MEMORIES_PER_SERIES;

const NB_COMMUTED_OCTADS = 8;
const NB_MEMORIES_PER_OCTAD = 8;

const NB_GENERAL_MEMORIES = 8;
const NB_OTHER_MEMORIES = NB_MEMORIES_PER_OCTAD * NB_COMMUTED_OCTADS;

const NB_BLOCKS_PER_MEMORY = 12;

MEMORY_MODE = {
  BINARY: {value: 0, name: "binary", code: "b"},
  DECIMAL: {value: 1, name: "decimal", code: "d"}
};
Object.freeze(MEMORY_MODE);


module.exports.NB_GENERAL_SERIES = NB_GENERAL_SERIES;
module.exports.NB_MEMORIES_PER_SERIES = NB_MEMORIES_PER_SERIES;
module.exports.NB_INST_IOSERIES = NB_INST_IOSERIES;
module.exports.NB_INST_PER_MEM = NB_INST_PER_MEM;
module.exports.NB_INST_PER_SERIES = NB_INST_PER_SERIES;

module.exports.NB_COMMUTED_OCTADS = NB_COMMUTED_OCTADS;
module.exports.NB_MEMORIES_PER_OCTAD = NB_MEMORIES_PER_OCTAD;

module.exports.NB_GENERAL_MEMORIES = NB_GENERAL_MEMORIES;
module.exports.NB_OTHER_MEMORIES = NB_OTHER_MEMORIES;

module.exports.NB_BLOCKS_PER_MEMORY = NB_BLOCKS_PER_MEMORY;

module.exports.MEMORY_MODE = MEMORY_MODE;
