const NB_GENERAL_SERIES = 3;
const NB_MEMORIES_PER_SERIES = 16;
const NB_INST_IOSERIES = 64;
const NB_INST_PER_MEM = 4;
const NB_INST_PER_SERIES = NB_INST_PER_MEM * NB_MEMORIES_PER_SERIES;

const NB_COMMUTED_OCTADS = 8;
const NB_MEMORIES_PER_OCTAD = 8;

const NB_GENERAL_MEMORIES = 8;
const NB_OTHER_MEMORIES = NB_MEMORIES_PER_OCTAD * NB_COMMUTED_OCTADS;

const NB_BLOCKS_PER_MEMORY = 12;
const NB_BLOCKS_LINE_NUMBER = 2;

const NB_OCTADS_PER_DRUM_BLOCK = 2;
const NB_BLOCKS_PER_DRUM_TRACK = 8;
const NB_TRACKS_PER_DRUM_TRACK_GROUP = 16
const NB_TRACK_GROUPS = 8;

MEMORY_MODE = {
  BINARY: {value: 0, name: "binary", code: "b"},
  DECIMAL: {value: 1, name: "decimal", code: "d"}
};
Object.freeze(MEMORY_MODE);


module.exports.NB_GENERAL_SERIES = NB_GENERAL_SERIES;
module.exports.NB_MEMORIES_PER_SERIES = NB_MEMORIES_PER_SERIES;
module.exports.NB_INST_IOSERIES = NB_INST_IOSERIES;
module.exports.NB_INST_PER_MEM = NB_INST_PER_MEM;
module.exports.NB_INST_PER_SERIES = NB_INST_PER_SERIES;

module.exports.NB_COMMUTED_OCTADS = NB_COMMUTED_OCTADS;
module.exports.NB_MEMORIES_PER_OCTAD = NB_MEMORIES_PER_OCTAD;

module.exports.NB_GENERAL_MEMORIES = NB_GENERAL_MEMORIES;
module.exports.NB_OTHER_MEMORIES = NB_OTHER_MEMORIES;

module.exports.NB_BLOCKS_PER_MEMORY = NB_BLOCKS_PER_MEMORY;
module.exports.NB_BLOCKS_LINE_NUMBER = NB_BLOCKS_LINE_NUMBER;

module.exports.NB_OCTADS_PER_DRUM_BLOCK = NB_OCTADS_PER_DRUM_BLOCK;
module.exports.NB_BLOCKS_PER_DRUM_TRACK = NB_BLOCKS_PER_DRUM_TRACK;
module.exports.NB_TRACKS_PER_DRUM_TRACK_GROUP = NB_TRACKS_PER_DRUM_TRACK_GROUP;
module.exports.NB_TRACK_GROUPS = NB_TRACK_GROUPS;

module.exports.MEMORY_MODE = MEMORY_MODE;
