@startuml
class mainVue {
}

class wirePannel {
}
mainVue *-- wirePannel

class editors {
}
mainVue *-- editors

class hexEditor {
}
editors *-- hexEditor

class debug {
  breakpoints
  setBreakPoints()
}
mainVue *-- debug

class memories {
  edit()
}
debug *--- memories

class octads {
  edit()
  selectOctad()
}
debug *--- octads

class series {
  @Output breakpts_emit
  setBreakPoint()
  selectSeries()
}
debug *--- series

class execution {
  @Input breakpoints
  execNextInstruction()
  execUntilBreakPoint()
}
debug *-- execution
@enduml
